# ============================================
#          EdenCells Configuration
#        Prison Cell Management System
# ============================================

# General plugin settings
general:
  # Enable debug mode for troubleshooting (shows extra logs)
  debug: false
  
  # Plugin language/locale (future feature)
  locale: "en_US"

# ============================================
#              MESSAGES & DISPLAY
# ============================================
messages:
  # Plugin prefix shown in all messages
  prefix: "<color:#9D4EDD>[EdenCells]</color> "
  
  # Color scheme for messages (uses MiniMessage format)
  colors:
    primary: "#9D4EDD"     # Vibrant purple - headers/titles
    secondary: "#06FFA5"   # Bright cyan - regular text
    accent: "#FFB3C6"      # Soft pink - highlights/values
    error: "#FF6B6B"       # Coral red - errors/warnings
    success: "#51CF66"     # Fresh green - success messages
    neutral: "#ADB5BD"     # Light gray - neutral/info text

# ============================================
#              CELL MANAGEMENT
# ============================================
cells:
  # Maximum cells a player can own (-1 for unlimited)
  max-per-player: 10
  
  # Default maximum members per cell (-1 for unlimited)
  default-max-members: 5
  
  # Keywords that identify cell signs (case-insensitive)
  sign-keywords:
    - "[Cell]"
    - "Cell"
    - "Prison Cell"
    - "[EdenCells]"
  
  # Cell GUI settings
  gui:
    # Items shown per page in cell lists
    items-per-page: 45
    # Default sort method: name, price, date, type
    default-sort: "name"
    # Show prices in GUIs
    show-prices: true
    # Show expiration dates for rentals
    show-expiration: true
    # Require confirmation for dangerous actions
    require-confirmation: true
    # Play click sounds in GUIs
    click-sounds: true

# ============================================
#                ECONOMY
# ============================================
economy:
  # Currency formatting (if not using Vault)
  currency-symbol: "$"
  currency-suffix: ""
  
  # Member management costs
  members:
    add-cost: 100.0      # Cost to add a member
    remove-cost: 50.0    # Cost to remove a member
  
  # Cell purchase/rental fees
  fees:
    # Percentage fee when selling a cell (0.0 - 1.0)
    sell-fee-percent: 0.1
    # Flat fee for listing a cell
    listing-fee: 0.0

# ============================================
#              CELL GROUPS
# ============================================

# Cell groups are now configured in cell-groups.yml for better organization
# This allows easier management and prevents config conflicts
# See cell-groups.yml for group configuration

# ============================================
#              TELEPORTATION
# ============================================
teleportation:
  # Base teleport cost (can be overridden per group)
  base-cost: 50.0
  
  # Whether teleportation requires payment
  require-payment: true
  
  # Cooldown between teleports (seconds)
  cooldown: 5
  
  # Groups that get free teleportation
  # Add group names here - supports multiple permission formats:
  # - "king" will check: group.king, edencells.group.king, and king
  # - You can use any permission name you want
  free-groups: []  # Example: ["king", "vip", "admin"]
  
  # Teleport effects
  effects:
    # Play sound on teleport
    play-sound: true
    sound: "entity.enderman.teleport"
    # Show particle effects
    show-particles: true
    particle: "PORTAL"

# ============================================
#              DOOR SYSTEM
# ============================================
doors:
  # Materials that can be linked as cell doors
  valid-materials:
    - IRON_DOOR
    - OAK_DOOR
    - SPRUCE_DOOR
    - BIRCH_DOOR
    - JUNGLE_DOOR
    - ACACIA_DOOR
    - DARK_OAK_DOOR
    - CRIMSON_DOOR
    - WARPED_DOOR
    - IRON_TRAPDOOR
  
  # Sound settings
  sounds:
    enabled: true
    open-sound: "block.iron_door.open"
    close-sound: "block.iron_door.close"
    volume: 1.0
    pitch: 1.0
  
  # Auto-close doors after X seconds (0 to disable)
  auto-close-delay: 0

# ============================================
#              SECURITY & LIMITS
# ============================================
security:
  # Rate limiting (actions per minute)
  rate-limits:
    cell-purchase: 3
    member-add: 5
    member-remove: 5
    door-interact: 20
    gui-open: 10
    npc-interact: 10
    bulk-add: 2  # Bulk operations per minute (to prevent server lag)
  
  # Input validation
  validation:
    # Maximum length for region IDs
    max-region-id-length: 32
    # Regex pattern for valid region IDs
    region-id-pattern: "^[a-zA-Z0-9_-]+$"
    # Maximum economy transaction amount
    max-transaction: 1000000.0
  
  # Audit logging
  audit:
    # Enable audit logging for important actions
    enabled: true
    # Log file location (relative to plugin folder)
    log-file: "logs/audit.log"
    # Actions to log
    log-actions:
      - "cell_purchase"
      - "cell_sell"
      - "member_add"
      - "member_remove"
      - "door_link"
      - "npc_teleport"

# ============================================
#              INTEGRATIONS
# ============================================
integrations:
  # AdvancedRegionMarket settings
  arm:
    # Use ARM's economy system
    use-arm-economy: true
    # Sync cell data with ARM
    sync-data: true
    # Check ARM permissions
    check-permissions: true
  
  # Citizens NPC settings
  citizens:
    # Enable Citizens integration for NPCs
    enabled: true
    # NPC name format
    npc-name-format: "&b&lCell Teleporter"
    # NPC skin (player name or URL)
    npc-skin: "Notch"
  
  # WorldGuard settings
  worldguard:
    # Check WorldGuard regions for cell access
    check-regions: true
    # Respect WorldGuard flags
    respect-flags: true

# ============================================
#              PERFORMANCE
# ============================================
performance:
  # Cache settings
  cache:
    # Cache player data (minutes)
    player-cache-time: 5
    # Cache region data (minutes)
    region-cache-time: 10
    # Maximum cache size
    max-cache-size: 1000
  
  # Async operations
  async:
    # Use async for file operations
    async-saves: true
    # Use async for economy transactions
    async-economy: true
    # Thread pool size
    thread-pool-size: 4

# ============================================
#              MAINTENANCE
# ============================================
maintenance:
  # Auto-save interval (minutes, 0 to disable)
  auto-save-interval: 5
  
  # Backup settings
  backup:
    # Enable automatic backups
    enabled: false
    # Backup interval (hours)
    interval: 24
    # Maximum backups to keep
    max-backups: 7
    # Backup folder (relative to plugin folder)
    folder: "backups"
  
  # Cleanup settings
  cleanup:
    # Remove expired rental data
    remove-expired-rentals: true
    # Days to keep audit logs
    audit-log-retention: 30
    # Clean orphaned door links
    clean-orphaned-doors: true

# ============================================
# Don't modify this - used for config updates
config-version: 2